--Even Fibonacci numbers
--
--Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
--
--    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--
--    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

f (x:y:[]) | x > 4000000 = 0 
f (x:y:[]) = if mod x 2 == 0 && x <= 4000000 then x+f([y, x+y]) else f([y, x+y])

main = print (f [1,2])
