"""
Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

print sum([i for i in reduce(lambda x,y: x+[x[-1]+x[-2]], range(30), [1,2]) if i <= 4*(10**6) and i%2==0])
